// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"


void on_callback(lv_event_t *e)
{
	turnOnMotor(0x0);
}

void off_callback(lv_event_t *e)
{
	turnOffMotor();
}
